### ISSUE TITLE
Document whether RollingHash is thread-safe

### ISSUE THREAD

**Issue by Rabadash8820** [SnowflakePowered/vcdiff#10]
Hello and thanks for maintaining this project! The API docs for the `rollingHash` param of the  `VcEncoder.Encode` method state:

> Manually provide a `VCDiff.Encoders.RollingHash` instance that can be reused for multiple encoding instances of the same block size. If you provide a `VCDiff.Encoders.RollingHash` instance, you must dispose of it yourself

However, I can't tell for sure whether `RollingHash` can be used by multiple encoding instances that are running _in parallel_. Is `RollingHash` thread-safe? It would be great to document this either in the API docs or somewhere in this repo.

**Comment by chyyran** [comment]
`RollingHash` is never mutated once created so it should be safe to use in parallel.

**Comment by Rabadash8820** [comment]
Sounds good; thanks for getting back to me. The main field I was concerned about is `v_shuf`. I see it referenced on [this line](https://github.com/SnowflakePowered/vcdiff/blob/f425c6a4aa896b26a49be113e5c633fbf0ee8210/src/VCDiff/Encoders/RollingHash.cs#L91) (shown below) and wasn't sure if that mutates `v_shuf` (I don't know much about AVX2).

```cs
c_v = Avx2.PermuteVar8x32(c_v, v_shuf);
```

Also, to be clear, this Issue was about _documenting_ whether `RollingHash` is thread-safe, as I'm sure other users of this library might wonder if it can be used in a multi-threaded environment. Pinning this Issue is a start, but it would be good to have this info in the Readme.

**Comment by chyyran** [comment]
No worries, I'm a bit backed up on things at the moment so I'll be updating the documentation when I get the chance.

For reference, `Avx2.PermuteVar8x32` is a shim for [`_mm256_permutevar8x32_epi32`](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/mm256-permutevar8x32-epi32.html), which doesn't mutate its arguments in place.

**Comment by Rabadash8820** [comment]
Sounds good, thanks for your help!
